name: 'queries'
version: '1.0.0'
config-version: 2

profile: 'crm'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  +persist_docs:
    relation: true
    columns: true
  queries:
    raw:
      +materialized: table
      bcadastro:
        +schema: brutos_bcadastro
    intermediate:
      +materialized: ephemeral
    core:
      +materialized: table
      +schema: dados_mestres

seeds:
  +schema: brutos_seeds
