crm:
  target: dev
  outputs:
    dev:
      dataset: dbt
      job_execution_timeout_seconds: 600
      job_retries: 1
      keyfile: /tmp/credentials.json
      location: US
      method: service-account
      priority: interactive
      project: rj-crm-registry-dev
      threads: 1
      type: bigquery
    staging:
      dataset: dbt
      job_execution_timeout_seconds: 600
      job_retries: 1
      keyfile: /tmp/credentials.json
      location: US
      method: service-account
      priority: interactive
      project: rj-crm-registry-dev
      threads: 1
      type: bigquery
    prod:
      dataset: dbt
      job_execution_timeout_seconds: 600
      job_retries: 1
      keyfile: /tmp/credentials.json
      location: US
      method: service-account
      priority: interactive
      project: rj-crm-registry
      threads: 1
      type: bigquery