crm:
  target: dev
  outputs:
    dev:
      dataset: dbt
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: credentials/credentials.json
      location: US
      method: service-account
      priority: interactive
      project: rj-crm-registry
      threads: 4
      type: bigquery
