version: 2


# TODO: Add freshness
sources:
  - name: disparos
    database: rj-iplanrio #?
    schema: disparos
    tables:
      - name: fluxo_atendimento
        description: "Tabela com dados de envio, entrega e leitura de mensagens do fluxo de atendimento"
      - name: atendimento_iniciado
        description: "Tabela com dados de atendimentos iniciados"
      - name: atendimento_finalizado
        description: "Tabela com dados de atendimentos finalizados"
      - name: fluxos_ura
        description: "Tabela com dados de URA"

models:
  - name: chatbot_atendimento
    description: "Métricas diárias de envio, entrega e leitura de mensagens do fluxo de atendimento"
    columns:
      - name: data
        description: "Data de envio das mensagens"
        data_type: date
        tests:
          - not_null

      - name: templateId
        description: "ID do template de disparo"
        data_type: string
        tests:
          - not_null

      - name: total_enviados
        description: "Número total de mensagens enviadas no dia"
        data_type: integer
        tests:
          - not_null

      - name: total_entregues
        description: "Número total de mensagens entregues no dia"
        data_type: integer
        tests:
          - not_null

      - name: total_lidos
        description: "Número total de mensagens lidas no dia"
        data_type: integer
        tests:
          - not_null

      - name: total_respondidos
        description: "Número total de mensagens respondidas no dia"
        data_type: integer
        tests:
          - not_null

      - name: taxa_entrega_percentual # 2
        description: "Percentual de mensagens entregues em relação às enviadas"
        data_type: numeric(5,2)
        tests:
          - not_null

      - name: taxa_leitura_percentual
        description: "Percentual de mensagens lidas em relação às entregues"
        data_type: numeric(5,2)
        tests:
          - not_null

      - name: taxa_resposta_percentual
        description: "Percentual de mensagens respondidas em relação às entregues"
        data_type: numeric(5,2)
        tests:
          - not_null

      - name: tempo_medio_entrega_segundos
        description: "Tempo médio em segundos entre o envio e a entrega das mensagens"
        data_type: numeric(10,2)
        tests:
          - not_null

      - name: tempo_medio_leitura_segundos
        description: "Tempo médio em segundos entre a entrega e a leitura das mensagens"
        data_type: numeric(10,2)
        tests:
          - not_null

      - name: tempo_medio_resposta_segundos
        description: "Tempo médio em segundos entre a entrega e a resposta das mensagens"
        data_type: numeric(10,2)
        tests:
          - not_null

      - name: tempo_medio_segundos
        description: "Tempo médio total da sessão HSM URA em segundos"
        data_type: numeric(10,2)
        tests:
          - not_null

  - name: chatbot_finalstatus
    description: Análise de conclusão dos fluxos de atendimento por WhatsApp por etapa
    columns:
      - name: atendimento_id
        description: ID do atendimento
        tests:
          - not_null
      - name: account
        description: Conta associada ao atendimento
        tests:
          - not_null
      - name: protocol
        description: Protocolo do atendimento
      - name: channel
        description: Canal do atendimento
      - name: data_inicio
        description: Data de início do atendimento
        tests:
          - not_null
      - name: tabulation
        description: ID da tabulação final
      - name: status_finalizacao
        description: Status descritivo da finalização do atendimento
        tests:
          - not_null

  - name: chatbot_optout
    description: Análise de opt-out (cancelamentos) nos fluxos de atendimento
    columns:
      - name: data_envio
        description: Data de envio da mensagem
        tests:
          - not_null
      - name: templateId
        description: ID do template da mensagem
        tests:
          - not_null
      - name: total_mensagens
        description: Total de mensagens enviadas
        tests:
          - not_null
      - name: total_opt_outs
        description: Total de opt-outs (tabulation_id = 35)
        tests:
          - not_null
      - name: taxa_opt_out
        description: Taxa de opt-out em percentual
        tests:
          - not_null

  - name: chatbot_responsetime
    description: Análise de tempos de resposta por etapa do fluxo
    columns:
      - name: data_envio
        description: Data de envio da mensagem
        tests:
          - not_null
      - name: templateId
        description: ID do template da mensagem
        tests:
          - not_null
      - name: total_mensagens
        description: Total de mensagens enviadas na etapa
        tests:
          - not_null
      - name: tempo_medio_entrega
        description: Tempo médio de entrega em segundos para a etapa
      - name: tempo_medio_leitura
        description: Tempo médio de leitura em segundos para a etapa
      - name: tempo_medio_resposta
        description: Tempo médio de resposta em segundos para a etapa
      - name: respostas_por_etapa
        description: Quantidade de respostas recebidas na etapa do fluxo
        tests:
          - not_null
      - name: tempo_resistencia
        description: Flag indicando se o tempo médio de resposta na etapa é maior que 1 hora (True/False)
        data_type: boolean
      - name: id_ura
        description: ID da URA associada à resposta
      - name: ura_name
        description: Nome da URA associada à resposta

