name: Trigger Documentation Update

on:
  push:
    branches: [ master, main ]
    paths:
      - 'models/**/*.sql'
      - 'models/**/*.yml'

jobs:
  trigger-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger documentation update
        run: |
          response=$(curl -s -w "%{http_code}" -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.DOCS_UPDATE_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/prefeitura-rio/mintlify-docs/dispatches \
            -d '{
              "event_type": "dbt-schema-updated",
              "client_payload": {
                "repository": "${{ github.repository }}",
                "ref": "${{ github.ref }}",
                "sha": "${{ github.sha }}",
                "changed_files": "models"
              }
            }')
          
          http_code="${response: -3}"
          
          if [ "$http_code" -eq 204 ]; then
            echo "✅ Successfully triggered documentation update"
          else
            echo "❌ Failed to trigger documentation update. HTTP code: $http_code"
            echo "Response: ${response%???}"
            exit 1
          fi